name: Android CI

on:
  push:
    branches: [ "develop", "release" ]
  pull_request:
    branches: [ "develop", "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # 최소 및 최대 API 레벨 설정
    strategy:
      matrix:
        api-level: [26, 34]
        target: [google_apis]
        include:
          - api-level: 26
            target: google_apis
          - api-level: 34
            target: google_apis

    steps:
    # 소스 코드를 체크아웃하는 단계
    - name: Checkout code
      uses: actions/checkout@v4

    # JDK 11 설정 단계
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Android SDK 설정 단계
    - name: Set up Android SDK 
      uses: android-actions/setup-android@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        cache: true

    # Gradlew 권한 설정
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Gradle을 사용하여 프로젝트 빌드
    - name: Build with Gradle 
      run: ./gradlew build
